/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoCompanyAccessRouteImport } from './routes/no-company-access'
import { Route as PlatformAdminSetupRequiredRouteImport } from './routes/platform-admin-setup-required'
import { Route as SelectCompanyRouteImport } from './routes/select-company'
import { Route as SystemAdminRouteImport } from './routes/system-admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBackupRouteImport } from './routes/_app.backup'
import { Route as AppCaReviewRouteImport } from './routes/_app.ca-review'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppLedgerRouteImport } from './routes/_app.ledger'
import { Route as AppMastersRouteImport } from './routes/_app.masters'
import { Route as AppPartiesRouteImport } from './routes/_app.parties'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppQuotationsRouteImport } from './routes/_app.quotations'
import { Route as AppReceiptsRouteImport } from './routes/_app.receipts'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoCompanyAccessRoute = NoCompanyAccessRouteImport.update({
  id: '/no-company-access',
  path: '/no-company-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminSetupRequiredRoute =
  PlatformAdminSetupRequiredRouteImport.update({
    id: '/platform-admin-setup-required',
    path: '/platform-admin-setup-required',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectCompanyRoute = SelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminRoute = SystemAdminRouteImport.update({
  id: '/system-admin',
  path: '/system-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBackupRoute = AppBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppRoute,
} as any)
const AppCaReviewRoute = AppCaReviewRouteImport.update({
  id: '/ca-review',
  path: '/ca-review',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppMastersRoute = AppMastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/no-company-access': typeof NoCompanyAccessRoute
  '/platform-admin-setup-required': typeof PlatformAdminSetupRequiredRoute
  '/select-company': typeof SelectCompanyRoute
  '/system-admin': typeof SystemAdminRoute
  '/backup': typeof AppBackupRoute
  '/ca-review': typeof AppCaReviewRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/invoices': typeof AppInvoicesRoute
  '/ledger': typeof AppLedgerRoute
  '/masters': typeof AppMastersRoute
  '/parties': typeof AppPartiesRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/quotations': typeof AppQuotationsRoute
  '/receipts': typeof AppReceiptsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/no-company-access': typeof NoCompanyAccessRoute
  '/platform-admin-setup-required': typeof PlatformAdminSetupRequiredRoute
  '/select-company': typeof SelectCompanyRoute
  '/system-admin': typeof SystemAdminRoute
  '/backup': typeof AppBackupRoute
  '/ca-review': typeof AppCaReviewRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/invoices': typeof AppInvoicesRoute
  '/ledger': typeof AppLedgerRoute
  '/masters': typeof AppMastersRoute
  '/parties': typeof AppPartiesRoute
  '/products': typeof AppProductsRoute
  '/purchases': typeof AppPurchasesRoute
  '/quotations': typeof AppQuotationsRoute
  '/receipts': typeof AppReceiptsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/no-company-access': typeof NoCompanyAccessRoute
  '/platform-admin-setup-required': typeof PlatformAdminSetupRequiredRoute
  '/select-company': typeof SelectCompanyRoute
  '/system-admin': typeof SystemAdminRoute
  '/_app/backup': typeof AppBackupRoute
  '/_app/ca-review': typeof AppCaReviewRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/ledger': typeof AppLedgerRoute
  '/_app/masters': typeof AppMastersRoute
  '/_app/parties': typeof AppPartiesRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/receipts': typeof AppReceiptsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/no-company-access'
    | '/platform-admin-setup-required'
    | '/select-company'
    | '/system-admin'
    | '/backup'
    | '/ca-review'
    | '/categories'
    | '/customers'
    | '/invoices'
    | '/ledger'
    | '/masters'
    | '/parties'
    | '/products'
    | '/purchases'
    | '/quotations'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/login'
    | '/no-company-access'
    | '/platform-admin-setup-required'
    | '/select-company'
    | '/system-admin'
    | '/backup'
    | '/ca-review'
    | '/categories'
    | '/customers'
    | '/invoices'
    | '/ledger'
    | '/masters'
    | '/parties'
    | '/products'
    | '/purchases'
    | '/quotations'
    | '/receipts'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/contact'
    | '/login'
    | '/no-company-access'
    | '/platform-admin-setup-required'
    | '/select-company'
    | '/system-admin'
    | '/_app/backup'
    | '/_app/ca-review'
    | '/_app/categories'
    | '/_app/customers'
    | '/_app/invoices'
    | '/_app/ledger'
    | '/_app/masters'
    | '/_app/parties'
    | '/_app/products'
    | '/_app/purchases'
    | '/_app/quotations'
    | '/_app/receipts'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  NoCompanyAccessRoute: typeof NoCompanyAccessRoute
  PlatformAdminSetupRequiredRoute: typeof PlatformAdminSetupRequiredRoute
  SelectCompanyRoute: typeof SelectCompanyRoute
  SystemAdminRoute: typeof SystemAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-company-access': {
      id: '/no-company-access'
      path: '/no-company-access'
      fullPath: '/no-company-access'
      preLoaderRoute: typeof NoCompanyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin-setup-required': {
      id: '/platform-admin-setup-required'
      path: '/platform-admin-setup-required'
      fullPath: '/platform-admin-setup-required'
      preLoaderRoute: typeof PlatformAdminSetupRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-company': {
      id: '/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof SelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin': {
      id: '/system-admin'
      path: '/system-admin'
      fullPath: '/system-admin'
      preLoaderRoute: typeof SystemAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/backup': {
      id: '/_app/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AppBackupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ca-review': {
      id: '/_app/ca-review'
      path: '/ca-review'
      fullPath: '/ca-review'
      preLoaderRoute: typeof AppCaReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledger': {
      id: '/_app/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/masters': {
      id: '/_app/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof AppMastersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts': {
      id: '/_app/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBackupRoute: typeof AppBackupRoute
  AppCaReviewRoute: typeof AppCaReviewRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppMastersRoute: typeof AppMastersRoute
  AppPartiesRoute: typeof AppPartiesRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBackupRoute: AppBackupRoute,
  AppCaReviewRoute: AppCaReviewRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppMastersRoute: AppMastersRoute,
  AppPartiesRoute: AppPartiesRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  NoCompanyAccessRoute: NoCompanyAccessRoute,
  PlatformAdminSetupRequiredRoute: PlatformAdminSetupRequiredRoute,
  SelectCompanyRoute: SelectCompanyRoute,
  SystemAdminRoute: SystemAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
